### ISSUE TITLE
Error object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by jimmiles** [thedyze/save-image-extended-comfyui#1]
How to use this to make it save to a folder named for the date? ComfyUI has a built-in node to do this. I thought this node would use that syntax (%date:yyyy-MM-dd%). Or am I doing something wrong? Also thought this would help me choose a path. I can't believe how so many other UIs find path customizing trivial, but ComfyUI left out any easy way to choose image save path setting. Shouldn't it be in the Main settings menu? Anyway, I digress.

Error occurred when executing SaveImageExtended:

object of type 'NoneType' has no len()

  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 96, in get_output_data
    output_is_list = [False] * len(results[0])

**Comment by thedyze** [comment]
To achieve this, add a 'Get Date Time String' node. Then inside the Save Image Extended node, right click and choose 'convert foldername_prefix to input'. 
Finally, drag the output of the date node to the new input. Should also work for 'filename_prefix'. Let me know if it doesnt work as expected.

**Comment by jimmiles** [comment]
I found a better way buried in an issue discussion: " You can now use
--output-directory directory/path to set the output path."
https://github.com/comfyanonymous/ComfyUI/issues/96

**Comment by thedyze** [comment]
Glad you found something that works for you. Though reading through the
discussion, the --output-directory method doesn't seem to work that well
for some of the users.

Den fre 6 okt. 2023 kl 13:05 skrev Jim Miles ***@***.***>:

> I found a better way buried in an issue discussion: " You can now use
> --output-directory directory/path to set the output path."
> https://github.com/comfyanonymous/ComfyUI/issues/96
>

**Comment by thedyze** [comment]
Or were you referring to the screenshot at the bottom?

**Comment by vootox** [comment]
I have the same problem though mine is I can't find the 'Get Date Time String' custom node, I also don't know what 'JPS' is.
