### ISSUE TITLE
Save Metadata Not Saving

### ISSUE THREAD

**Issue by yaitsbilly** [thedyze/save-image-extended-comfyui#10]
Not sure if I'm missing something but I'm uploading an image to CivitAI and its not able to pull any of the metadata. 

![image](https://github.com/thedyze/save-image-extended-comfyui/assets/3598472/5b0d8b38-a962-4ed8-b14a-b9de893f2248)

![image](https://github.com/thedyze/save-image-extended-comfyui/assets/3598472/3496da7b-c265-47a8-8cbf-5e87630df326)

**Comment by thedyze** [comment]
Thanks for reporting, will look into this as soon as possible.

**Comment by thedyze** [comment]
Sorry, was not quite awake when I read the initial post :). I don't think comfyui ever officially has supported civitai metadata.

This option is for the comfy workflow to be included as metadata. 
I.e so you can drag a generated image (with save metadata on) into an empty workspace and comfy will magically create the workspace used. 
A quick google turned up this result, might help you? https://www.reddit.com/r/comfyui/comments/15trfah/comfyui_is_great_but_it_doesnt_save_appropriate/

Maybe something to add to this plugin later down the line.

**Comment by yaitsbilly** [comment]
Found this too, https://github.com/comfyanonymous/ComfyUI/issues/1182

**Comment by yaitsbilly** [comment]
I found this which can save it. https://github.com/zer0TF/cute-comfy Not sure if it's something you can grab off of it.

**Comment by thedyze** [comment]
Yeah, I don't think its 'just to grab it' 😁. Quoting their documentation:

"We can't always figure out where your stuff is inside of your Comfy workflow - Comfy is crazy! You could have 10 separate positive prompts, 4 model merges, and 5 different sampler steps!"

So adding this feature would most likely require _a lot_ of work to implement, and just as much work to maintain.
In the link I posted there is also a long discussion about the problems in trying to implement this with comfy.

Sorry to say, but I don't think it's something that will be added in the near future.
