### ISSUE TITLE
Unable to save positive prompt/negative prompt in json

### ISSUE THREAD

**Issue by franzkruhm** [thedyze/save-image-extended-comfyui#13]
So I have
![image](https://github.com/thedyze/save-image-extended-comfyui/assets/34811816/101b02d3-e0cb-4df5-85ac-c8eab7323f9f)

but I get just one "positive prompt" field in the json for each pic but it contains... the negative prompt

**Comment by thedyze** [comment]
Is it a standard or custom setup for the prompts?

**Comment by fipil** [comment]
I experienced the same wrong behaviour. 
A workaround is to create an extra primitive string nodes for the positive/negative prompts and connect them to the proper Clip Text encode positive/negative and also to the Save image extended positive_text_opt/negative_text_opt. 
Then it works, but it's quite additional work.

**Comment by fipil** [comment]
> Is it a standard or custom setup for the prompts?

I just created a new workflow by clicking to the Load Default. So imho it's standart setup for the prompt.

[workflow test Save Image Extended.json](https://github.com/thedyze/save-image-extended-comfyui/files/14075836/workflow.test.Save.Image.Extended.json)

[jobs.json](https://github.com/thedyze/save-image-extended-comfyui/files/14075838/jobs.json)

**Comment by dryodryo** [comment]
Hi, this is a bug that I am also experiencing. The JSON file includes a field for the "positive prompt" but it actually includes the negative prompt. I need both of them to be in the JSON file, and correctly labeled.

I was able to work around it by adding extra text nodes to drive the conditioning and the inputs on Save Image Extended. But this is almost certainly a simple fix in the python code. It would be great if this could be dealt with. Thanks!!

**Comment by addiGeometry** [comment]
Hello Everyone,

I had the same issue and fixed the code. I found a typo bug in Line 239 in save_image_extended.py.
Basically the positive prompt was overwritten by the negative one.
You can fix it yourself by correcting the line until it's fixed :)

![quick_fix](https://github.com/thedyze/save-image-extended-comfyui/assets/104462920/8b4192cf-d993-4165-abbd-90dc499dc917)
Just replace the second "positive_prompt" with "negative_prompt".

@thedyze 
@AlUlkesh

**Comment by dryodryo** [comment]
> I had the same issue and fixed the code.

Awesome, thanks. I knew it would be an easy fix.

**Comment by audioscavenger** [comment]
@addiGeometry please submit your PR [here](https://github.com/audioscavenger/save-image-extended-comfyui), thanks

**Comment by addiGeometry** [comment]
@audioscavenger Hey Eric. This is my first time contributing on github. I tried creating the pull request. let me know if it worked. Weirdly enough git seems to see way more changes then there actually were...
