### ISSUE TITLE
Feature Request: Accordion dropdown for widget rows

### ISSUE THREAD

**Issue by LuisBurdallo** [thedyze/save-image-extended-comfyui#16]
Would it be possible to have a way to hide every single widgets row so only the connectors and preview are visible? The only thing that puts me off is how much height space the node takes. I still use it but I wish I could minimize all those rows I never change.

**Comment by LuisBurdallo** [comment]
I am currently simply having that node minimized and I use a preview image node to avoid having that node open. I wonder if ComfyUI supports accordion/collapsible dropdowns because I haven't seen them yet in any node.

**Comment by audioscavenger** [comment]
That's a ComfyUI question. just click the top left buble to collapse it. but I agree you lose the preview as well. nothing i can do, sorry.
