### ISSUE TITLE
[feature request] outputs

### ISSUE THREAD

**Issue by drago87** [thedyze/save-image-extended-comfyui#2]
Would be nice to have an string output for folder name and file name if possible

**Comment by thedyze** [comment]
Can you describe in more detail the functionality you want?

Den tis 10 okt. 2023 kl 16:20 skrev drago87 ***@***.***>:

**Comment by drago87** [comment]
when it saves the image you have an optional output for the folder name and file name so you can for example save a  text file of the same name in the same folder

**Comment by thedyze** [comment]
Not following, this is exactly what this node does? :)

**Comment by drago87** [comment]
Ment a node output so you can add something after the image save

**Comment by thedyze** [comment]
Add something to the folder you mean? What did you have in mind to save in the text file?
Regarding the prompt, the 'save_job_data' option  can save the prompts in the generated folder

**Comment by drago87** [comment]
one thing you could save is if you upscale a image you can have the input image resolution in addotion to the output image or you can just some notes

**Comment by thedyze** [comment]
By adding the 'basic' option to the save_job_data, the input resolution is saved.

I guess a string input could be added, that way you could add custom text you wanted and save it to the json file with each generated job. Maybe something to add if there is more interest in it.

**Comment by thedyze** [comment]
I have now added a 'job_custom_text' parameter. Can be converted to an input. This way it's possible to save any text along with the rest of the job in the generated json.
