### ISSUE TITLE
Saving only 1500 files per folder

### ISSUE THREAD

**Issue by GraftingRayman** [thedyze/save-image-extended-comfyui#20]
Hi Everyone

I have been using save image extended to save pose files generated by DWPose Estimator

When saving, the save image extended node only saves 1500 per folder and skips the rest

If i have say 1200 files already in the folder, and want to save 500 more, it will only save 300 in that folder and skip the rest

If i change the folder name to something different, that folder has no contents it will save the full 500 till it reaches 1500

This is an issue with the node i believe as a normal save node works fine

If you can take a look at this limitation

**Comment by audioscavenger** [comment]
hi, that's interesting. I took over the project and will have a look if you [create an issue here](https://github.com/audioscavenger/save-image-extended-comfyui/issues)
