### ISSUE TITLE
Prompt in filename?

### ISSUE THREAD

**Issue by AlUlkesh** [thedyze/save-image-extended-comfyui#3]
Glad this repo exists, it was just what I was looking for.

Is there any way I could include the positive prompt in the filename?

**Comment by AlUlkesh** [comment]
Thank you!

I'm not using the efficiency loaders, but after your pointer I was able to get it to work with a key of "text_positive".

**Comment by Woisek** [comment]
Because related to prompt: Somehow, I don't get the prompts into the metadata of the image. I don't know if it's extension related or just me not knowing how to route in ComfyUI ... 😐

**Comment by AlUlkesh** [comment]
@Woisek 
Did you enable "save_metadata"?

**Comment by LockMan007** [comment]
filename_keys:
date,time,ckpt_name,positive_prompt,text_positive,text,positive
result:
sd_xl_turbo_1.0_fp16__['6', 0]

doesn't show date or time and doesn't show any prompt data.

**Comment by Woisek** [comment]
@AlUlkesh Yes, I did, but somehow it won't inset it. Only the 'technical' parts, no prompts.

**Comment by AlUlkesh** [comment]
@Woisek Can you upload your workflow? I could check why it behaves differently for me.

**Comment by Woisek** [comment]
@AlUlkesh I have to look for it. I changed and redone some things since the last time.
