### ISSUE TITLE
Counter does not work

### ISSUE THREAD

**Issue by AlUlkesh** [thedyze/save-image-extended-comfyui#4]
With this setting, the counter does not work. Instead the old picture is overwritten:

![image](https://github.com/thedyze/save-image-extended-comfyui/assets/99896447/a9b8aede-628d-4822-b1f2-8982d4ff66f2)

For example, if the image written last time was "000001_1.png", it will be overwritten.

**Comment by thedyze** [comment]
Thanks for reporting, will look into it.

**Comment by thedyze** [comment]
I've identified and fixed the issue. Will make a new release in the coming days.

**Comment by AlUlkesh** [comment]
Great! Thanks.

**Comment by thedyze** [comment]
Ok, updated the node. Please check that the issue is resolved for you.

**Comment by AlUlkesh** [comment]
Yes, no more overwriting, it's counted up now. Thanks for the quick fix!
