### ISSUE TITLE
[feature request] Independent Counter

### ISSUE THREAD

**Issue by AlUlkesh** [thedyze/save-image-extended-comfyui#5]
I think currently the counter is incremented if the rest of the filename is the same.

Would it possible to add an option that increments the counter independently from the rest of the filename?

For example, currently:
With the following files existing in the folder
```
000001_good_image.png
000003_bad_image.png
```
and generating another `good_image` the filename is: `000002_good_image.png`

My request would make it possible for the filename to be `000004_good_image.png` instead.

Or in other words, what I am looking for, is for each file in the folder to have its unique ascending number.

**Comment by AlUlkesh** [comment]
An easier approach might be to leave the current logic as is and introduce a new, separate, "sequence number", that when used is always at the beginning of the filename.

If you think that approach would work for you, I could make a PR for it.

**Comment by thedyze** [comment]
I might be open for that, let me get back to you.  Want think a bit on how to proceed first.

**Comment by thedyze** [comment]
Hey, totally forgot about this, sorry. Go ahead if you're still up for that PR!

**Comment by AlUlkesh** [comment]
Hi, ok, I'll look into it.

**Comment by aegis72** [comment]
Hi! The way I did this was to make my own "bitly" namer node setup, and then I concat that to the filename string. You can see it in the appendix of my Aegisflow Documentation (near the end of the PDF manual): https://github.com/aegis72/aegisflow

**Comment by AlUlkesh** [comment]
Sorry, I only got around to this today.

@aegis72: Thanks, however I prefer an ascending number in the filename, so I can sort with it.

@thedyze: I think I got this done today, but then I ran into issue #6, so I'll wait for the PR.
