### ISSUE TITLE
Older saves not compatible

### ISSUE THREAD

**Issue by AlUlkesh** [thedyze/save-image-extended-comfyui#6]
When I load an image, that was saved before this commit: https://github.com/thedyze/save-image-extended-comfyui/commit/d712114afa75dd61c9dde6c9cb896e8590212f6b

the fields are not properly aligned to their values.

For example, if I have an image which had this setting before that commit:

![image](https://github.com/thedyze/save-image-extended-comfyui/assets/99896447/e9c2d2c4-b980-4bd6-b159-cd065a0887f7)

and load it with the current commit I get this:

![image](https://github.com/thedyze/save-image-extended-comfyui/assets/99896447/458c698c-0fa2-4612-a029-9ca1649556b1)

**Comment by aegis72** [comment]
Thanks! I'll be sure not to update before it's resolved. Thanks for pointing this one out; took a second to see it but yeah, the new 'job custom text" field (a cool addition) seems to be the culprit, pushing fields/values around

**Comment by thedyze** [comment]
I think this might have to do with how comfy loads nodes. If you remove the node and re add it, does it resolve your issue?

**Comment by AlUlkesh** [comment]
Well, yes, but then everything is set to default and the saved info is lost.

I think it has something to do with this:

https://github.com/thedyze/save-image-extended-comfyui/blob/d712114afa75dd61c9dde6c9cb896e8590212f6b/save_image_extended.py#L260-L278

Since most of these are positional parameters, adding new ones in the middle messes up the handling of older files.

**Comment by thedyze** [comment]
That might be it yeah. Going forward I don't see myself adding much more parameters, but I'll keep that in mind.

Though if new params are added, they should preferably be grouped with other params belonging in to same category.
I do think the data lost is really not that hard to replace by hand?

**Comment by AlUlkesh** [comment]
> I do think the lost settings of the parameters is really not that hard to replace by hand?

Well, the issue is not tragic, but certainly annoying.

I looked a bit more into the ComfyUI code and it's actually this part that determines the load order:

https://github.com/thedyze/save-image-extended-comfyui/blob/d712114afa75dd61c9dde6c9cb896e8590212f6b/save_image_extended.py#L24-L46

So, yes, since this is a ComfyUI limitation, I don't think we can do much about it.

Perhaps I'll write a converter for the metadata inside the older images, when I get around to it.
