### ISSUE TITLE
the saved image node does not have  an output

### ISSUE THREAD

**Issue by jlitz** [thedyze/save-image-extended-comfyui#9]
the file name prefix  does not want to connect to the save extended mode

**Comment by aegis72** [comment]
Might want to show some more info there to assist in troubleshooting, but the one time I had this happen, I had forgotten to convert my data that I was trying to connect into a string (ie, if you are trying to pass an int f/e).

**Comment by jlitz** [comment]
Tnx for the response.
I am pretty new to  comfy but learning    I am unfamiliar with the terms pass an int f/e   Interesting how fast tech developes  Instant images while you type.

 This is the workflow SDXL.  My idea is to   create  a video with the  output.

![sdxlturbo_example](https://github.com/thedyze/save-image-extended-comfyui/assets/29810797/49e4c44f-8ea2-4446-9552-569f7b27a621)

![sdxlturbo_example](https://github.com/thedyze/save-image-extended-comfyui/assets/29810797/6ef4d79b-296c-4a0f-81a8-3c9d4e43b055)  Not sure why two different
  Page I made on Turbo links  fwiw  https://start.me/p/kvAgdd/sdxl-turbo

**Comment by thedyze** [comment]
That workflow does not contain the save-image-extended node?

Also, it would be more helpful if you described the problem in more detail, and/or post a screenshot. I was missing quite a few of the custom nodes you are using.

**Comment by jlitz** [comment]
[SDXL TURBO.json](https://github.com/thedyze/save-image-extended-comfyui/files/13550550/SDXL.TURBO.json)
![opera_m8IK3kWYls](https://github.com/thedyze/save-image-extended-comfyui/assets/29810797/bb88640b-ef13-41b0-8dfd-a0acb43345b1)
 
The workflow has the  has the extended save node  the image shows  which nodes do not attach   arrows

**Comment by jlitz** [comment]
OK got it working tnx for help
